Add wezterm, oil, and a whole bunch of other stuff

diff --git a/.bin/serve b/.bin/serve
--- a/.bin/serve
+++ b/.bin/serve
@@ -3,8 +3,8 @@
 # To kill a process listening on a certain TCP port:
 # ss -tpln | grep 44749 | awk '{print $6}' | cut -d ',' -f 2 | cut -d '=' -f 2
 
-if ! [ -x `command -v "python3"` ]; then
-    echo &>2 "Error: python3 required for HTTP serve"
+if ! command -v "python3" > /dev/null 2>&1; then
+    echo >&2 "Error: python3 required for HTTP serve"
     exit 1
 fi
 
